- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: latest

#Step 2 start and enables the service
- name: start and enabled services
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
# Step 3 delete the default website directoy
- name: app-pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: copy backend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx


    # below we put comment out bcs we are using handler if not user handler below coment should not keep 
# - name: restart the nginx service
#   ansible.builtin.service:
#     name: nginx
#     state: restarted
